-- MySQL Script generated by MySQL Workbench
-- Sun Jan  3 01:13:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PlantelEducativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlantelEducativo` (
  `clave` VARCHAR(100) NOT NULL,
  `sector` VARCHAR(100) NOT NULL,
  `nivelEscolar` VARCHAR(100) NOT NULL,
  `zona` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(200) NOT NULL,
  `PlantelEducativo_clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_Cuenta_PlantelEducativo1_idx` (`PlantelEducativo_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_PlantelEducativo1`
    FOREIGN KEY (`PlantelEducativo_clave`)
    REFERENCES `mydb`.`PlantelEducativo` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `idGenero` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docente` (
  `clave` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NOT NULL,
  `apellidoMaterno` VARCHAR(100) NOT NULL,
  `gradoAcademico` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_Docente_Cuenta_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  INDEX `fk_Docente_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_Cuenta`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `clave` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_Alumno_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  INDEX `fk_Alumno_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CicloEscolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CicloEscolar` (
  `idCicloEscolar` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFinal` DATE NOT NULL,
  PRIMARY KEY (`idCicloEscolar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foro` (
  `idForo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idForo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `CicloEscolar_idCicloEscolar` INT NOT NULL,
  `Foro_idForo` INT NOT NULL,
  `Docente_clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `fk_Grupo_CicloEscolar1_idx` (`CicloEscolar_idCicloEscolar` ASC) VISIBLE,
  INDEX `fk_Grupo_Foro1_idx` (`Foro_idForo` ASC) VISIBLE,
  INDEX `fk_Grupo_Docente1_idx` (`Docente_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_CicloEscolar1`
    FOREIGN KEY (`CicloEscolar_idCicloEscolar`)
    REFERENCES `mydb`.`CicloEscolar` (`idCicloEscolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Foro1`
    FOREIGN KEY (`Foro_idForo`)
    REFERENCES `mydb`.`Foro` (`idForo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Docente1`
    FOREIGN KEY (`Docente_clave`)
    REFERENCES `mydb`.`Docente` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GradoAcademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GradoAcademico` (
  `idGradoAcademico` INT NOT NULL AUTO_INCREMENT,
  `gradoAcademico` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGradoAcademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `GradoAcademico_idGradoAcademico` INT NOT NULL,
  PRIMARY KEY (`idMateria`),
  INDEX `fk_Materia_GradoAcademico1_idx` (`GradoAcademico_idGradoAcademico` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_GradoAcademico1`
    FOREIGN KEY (`GradoAcademico_idGradoAcademico`)
    REFERENCES `mydb`.`GradoAcademico` (`idGradoAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fechaCreada` DATE NOT NULL,
  `fechaEntrega` DATE NOT NULL,
  `calificacion` INT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  `Alumno_clave` VARCHAR(40) NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  INDEX `fk_Actividad_Alumno1_idx` (`Alumno_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Alumno1`
    FOREIGN KEY (`Alumno_clave`)
    REFERENCES `mydb`.`Alumno` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `archivo` BLOB NOT NULL,
  `Docente_clave` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `fk_Bitacora_Docente1_idx` (`Docente_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Bitacora_Docente1`
    FOREIGN KEY (`Docente_clave`)
    REFERENCES `mydb`.`Docente` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo_has_Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo_has_Alumno` (
  `Grupo_idGrupo` INT NOT NULL,
  `calificacion` INT NOT NULL,
  `Alumno_clave` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Grupo_idGrupo`),
  INDEX `fk_Grupo_has_Alumno_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Alumno_Alumno1_idx` (`Alumno_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Alumno_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_clave`)
    REFERENCES `mydb`.`Alumno` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia_has_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia_has_Grupo` (
  `Materia_idMateria` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Grupo_idGrupo`),
  INDEX `fk_Materia_has_Grupo_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  INDEX `fk_Materia_has_Grupo_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_has_Grupo_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Grupo_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `idBloque` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFinal` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `propositos` VARCHAR(200) NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idBloque`),
  INDEX `fk_Bloque_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Bloque_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno_has_Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno_has_Bloque` (
  `Alumno_clave` VARCHAR(40) NOT NULL,
  `Bloque_idBloque` INT NOT NULL,
  `calificacion` INT NOT NULL,
  PRIMARY KEY (`Alumno_clave`, `Bloque_idBloque`),
  INDEX `fk_Alumno_has_Bloque_Bloque1_idx` (`Bloque_idBloque` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Bloque_Alumno1_idx` (`Alumno_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Bloque_Alumno1`
    FOREIGN KEY (`Alumno_clave`)
    REFERENCES `mydb`.`Alumno` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Bloque_Bloque1`
    FOREIGN KEY (`Bloque_idBloque`)
    REFERENCES `mydb`.`Bloque` (`idBloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(200) NOT NULL,
  `Foro_idForo` INT NOT NULL,
  `Alumno_clave` VARCHAR(40) NULL,
  `Docente_clave` VARCHAR(40) NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_Mensaje_Foro1_idx` (`Foro_idForo` ASC) VISIBLE,
  INDEX `fk_Mensaje_Alumno1_idx` (`Alumno_clave` ASC) VISIBLE,
  INDEX `fk_Mensaje_Docente1_idx` (`Docente_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_Foro1`
    FOREIGN KEY (`Foro_idForo`)
    REFERENCES `mydb`.`Foro` (`idForo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Alumno1`
    FOREIGN KEY (`Alumno_clave`)
    REFERENCES `mydb`.`Alumno` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Docente1`
    FOREIGN KEY (`Docente_clave`)
    REFERENCES `mydb`.`Docente` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Archivo` (
  `idArchivo` INT NOT NULL AUTO_INCREMENT,
  `archivo` BLOB NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idArchivo`, `Actividad_idActividad`),
  INDEX `fk_Archivo_Actividad1_idx` (`Actividad_idActividad` ASC) VISIBLE,
  CONSTRAINT `fk_Archivo_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Docente_has_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docente_has_Materia` (
  `Docente_clave` VARCHAR(100) NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Docente_clave`, `Materia_idMateria`),
  INDEX `fk_Docente_has_Materia_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  INDEX `fk_Docente_has_Materia_Docente1_idx` (`Docente_clave` ASC) VISIBLE,
  CONSTRAINT `fk_Docente_has_Materia_Docente1`
    FOREIGN KEY (`Docente_clave`)
    REFERENCES `mydb`.`Docente` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
